package com.gramasuvidha.portal

import android.app.Application
import android.content.Context
import com.gramasuvidha.portal.data.local.AppDatabase
import com.gramasuvidha.portal.data.local.entities.ProjectEntity
import com.gramasuvidha.portal.data.repository.ProjectRepository
import com.gramasuvidha.portal.util.LocaleHelper
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch

class GramaApplication : Application() {

    private val applicationScope = CoroutineScope(SupervisorJob())

    override fun attachBaseContext(base: Context) {
        super.attachBaseContext(LocaleHelper.onAttach(base))
    }

    override fun onCreate() {
        super.onCreate()
        
        val database = AppDatabase.getDatabase(this)
        val repository = ProjectRepository(database.projectDao(), database.feedbackDao())
        
        applicationScope.launch {
            // Clear existing projects to ensure the list is updated correctly
            repository.deleteAllProjects()

            val allProjects = listOf(
                ProjectEntity(
                    getString(R.string.proj_1_id), 
                    getString(R.string.proj_1_name_en), 
                    getString(R.string.proj_1_name_kn), 
                    getString(R.string.proj_1_location_en),
                    getString(R.string.proj_1_location_kn),
                    getString(R.string.proj_1_budget), 
                    getString(R.string.proj_1_date),
                    getString(R.string.proj_1_status_en), 
                    getString(R.string.proj_1_status_kn), 
                    85, 
                    getString(R.string.proj_1_desc_en), 
                    getString(R.string.proj_1_desc_kn), 
                    getString(R.string.proj_1_before_img), 
                    getString(R.string.proj_1_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_2_id), 
                    getString(R.string.proj_2_name_en), 
                    getString(R.string.proj_2_name_kn), 
                    getString(R.string.proj_2_location_en),
                    getString(R.string.proj_2_location_kn),
                    getString(R.string.proj_2_budget), 
                    getString(R.string.proj_2_date),
                    getString(R.string.proj_2_status_en), 
                    getString(R.string.proj_2_status_kn), 
                    100, 
                    getString(R.string.proj_2_desc_en), 
                    getString(R.string.proj_2_desc_kn), 
                    getString(R.string.proj_2_before_img), 
                    getString(R.string.proj_2_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_3_id), 
                    getString(R.string.proj_3_name_en), 
                    getString(R.string.proj_3_name_kn), 
                    getString(R.string.proj_3_location_en),
                    getString(R.string.proj_3_location_kn),
                    getString(R.string.proj_3_budget), 
                    getString(R.string.proj_3_date),
                    getString(R.string.proj_3_status_en), 
                    getString(R.string.proj_3_status_kn), 
                    0, 
                    getString(R.string.proj_3_desc_en), 
                    getString(R.string.proj_3_desc_kn), 
                    getString(R.string.proj_3_before_img), 
                    getString(R.string.proj_3_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_001_id),
                    getString(R.string.proj_001_name_en),
                    getString(R.string.proj_001_name_kn),
                    getString(R.string.proj_001_location_en),
                    getString(R.string.proj_001_location_kn),
                    getString(R.string.proj_001_budget),
                    getString(R.string.proj_001_date),
                    getString(R.string.proj_001_status_en),
                    getString(R.string.proj_001_status_kn),
                    72,
                    getString(R.string.proj_001_desc_en),
                    getString(R.string.proj_001_desc_kn),
                    getString(R.string.proj_001_before_img),
                    getString(R.string.proj_001_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_002_id),
                    getString(R.string.proj_002_name_en),
                    getString(R.string.proj_002_name_kn),
                    getString(R.string.proj_002_location_en),
                    getString(R.string.proj_002_location_kn),
                    getString(R.string.proj_002_budget),
                    getString(R.string.proj_002_date),
                    getString(R.string.proj_002_status_en),
                    getString(R.string.proj_002_status_kn),
                    100,
                    getString(R.string.proj_002_desc_en),
                    getString(R.string.proj_002_desc_kn),
                    getString(R.string.proj_002_before_img),
                    getString(R.string.proj_002_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_003_id),
                    getString(R.string.proj_003_name_en),
                    getString(R.string.proj_003_name_kn),
                    getString(R.string.proj_003_location_en),
                    getString(R.string.proj_003_location_kn),
                    getString(R.string.proj_003_budget),
                    getString(R.string.proj_003_date),
                    getString(R.string.proj_003_status_en),
                    getString(R.string.proj_003_status_kn),
                    45,
                    getString(R.string.proj_003_desc_en),
                    getString(R.string.proj_003_desc_kn),
                    getString(R.string.proj_003_before_img),
                    getString(R.string.proj_003_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_004_id),
                    getString(R.string.proj_004_name_en),
                    getString(R.string.proj_004_name_kn),
                    getString(R.string.proj_004_location_en),
                    getString(R.string.proj_004_location_kn),
                    getString(R.string.proj_004_budget),
                    getString(R.string.proj_004_date),
                    getString(R.string.proj_004_status_en),
                    getString(R.string.proj_004_status_kn),
                    10,
                    getString(R.string.proj_004_desc_en),
                    getString(R.string.proj_004_desc_kn),
                    getString(R.string.proj_004_before_img),
                    getString(R.string.proj_004_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_005_id),
                    getString(R.string.proj_005_name_en),
                    getString(R.string.proj_005_name_kn),
                    getString(R.string.proj_005_location_en),
                    getString(R.string.proj_005_location_kn),
                    getString(R.string.proj_005_budget),
                    getString(R.string.proj_005_date),
                    getString(R.string.proj_005_status_en),
                    getString(R.string.proj_005_status_kn),
                    60,
                    getString(R.string.proj_005_desc_en),
                    getString(R.string.proj_005_desc_kn),
                    getString(R.string.proj_005_before_img),
                    getString(R.string.proj_005_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_006_id),
                    getString(R.string.proj_006_name_en),
                    getString(R.string.proj_006_name_kn),
                    getString(R.string.proj_006_location_en),
                    getString(R.string.proj_006_location_kn),
                    getString(R.string.proj_006_budget),
                    getString(R.string.proj_006_date),
                    getString(R.string.proj_006_status_en),
                    getString(R.string.proj_006_status_kn),
                    85,
                    getString(R.string.proj_006_desc_en),
                    getString(R.string.proj_006_desc_kn),
                    getString(R.string.proj_006_before_img),
                    getString(R.string.proj_006_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_007_id),
                    getString(R.string.proj_007_name_en),
                    getString(R.string.proj_007_name_kn),
                    getString(R.string.proj_007_location_en),
                    getString(R.string.proj_007_location_kn),
                    getString(R.string.proj_007_budget),
                    getString(R.string.proj_007_date),
                    getString(R.string.proj_007_status_en),
                    getString(R.string.proj_007_status_kn),
                    100,
                    getString(R.string.proj_007_desc_en),
                    getString(R.string.proj_007_desc_kn),
                    getString(R.string.proj_007_before_img),
                    getString(R.string.proj_007_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_008_id),
                    getString(R.string.proj_008_name_en),
                    getString(R.string.proj_008_name_kn),
                    getString(R.string.proj_008_location_en),
                    getString(R.string.proj_008_location_kn),
                    getString(R.string.proj_008_budget),
                    getString(R.string.proj_008_date),
                    getString(R.string.proj_008_status_en),
                    getString(R.string.proj_008_status_kn),
                    30,
                    getString(R.string.proj_008_desc_en),
                    getString(R.string.proj_008_desc_kn),
                    getString(R.string.proj_008_before_img),
                    getString(R.string.proj_008_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_009_id),
                    getString(R.string.proj_009_name_en),
                    getString(R.string.proj_009_name_kn),
                    getString(R.string.proj_009_location_en),
                    getString(R.string.proj_009_location_kn),
                    getString(R.string.proj_009_budget),
                    getString(R.string.proj_009_date),
                    getString(R.string.proj_009_status_en),
                    getString(R.string.proj_009_status_kn),
                    90,
                    getString(R.string.proj_009_desc_en),
                    getString(R.string.proj_009_desc_kn),
                    getString(R.string.proj_009_before_img),
                    getString(R.string.proj_009_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_010_id),
                    getString(R.string.proj_010_name_en),
                    getString(R.string.proj_010_name_kn),
                    getString(R.string.proj_010_location_en),
                    getString(R.string.proj_010_location_kn),
                    getString(R.string.proj_010_budget),
                    getString(R.string.proj_010_date),
                    getString(R.string.proj_010_status_en),
                    getString(R.string.proj_010_status_kn),
                    5,
                    getString(R.string.proj_010_desc_en),
                    getString(R.string.proj_010_desc_kn),
                    getString(R.string.proj_010_before_img),
                    getString(R.string.proj_010_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_011_id),
                    getString(R.string.proj_011_name_en),
                    getString(R.string.proj_011_name_kn),
                    getString(R.string.proj_011_location_en),
                    getString(R.string.proj_011_location_kn),
                    getString(R.string.proj_011_budget),
                    getString(R.string.proj_011_date),
                    getString(R.string.proj_011_status_en),
                    getString(R.string.proj_011_status_kn),
                    55,
                    getString(R.string.proj_011_desc_en),
                    getString(R.string.proj_011_desc_kn),
                    getString(R.string.proj_011_before_img),
                    getString(R.string.proj_011_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_012_id),
                    getString(R.string.proj_012_name_en),
                    getString(R.string.proj_012_name_kn),
                    getString(R.string.proj_012_location_en),
                    getString(R.string.proj_012_location_kn),
                    getString(R.string.proj_012_budget),
                    getString(R.string.proj_012_date),
                    getString(R.string.proj_012_status_en),
                    getString(R.string.proj_012_status_kn),
                    40,
                    getString(R.string.proj_012_desc_en),
                    getString(R.string.proj_012_desc_kn),
                    getString(R.string.proj_012_before_img),
                    getString(R.string.proj_012_after_img)
                ),
                ProjectEntity(
                    getString(R.string.proj_013_id),
                    getString(R.string.proj_013_name_en),
                    getString(R.string.proj_013_name_kn),
                    getString(R.string.proj_013_location_en),
                    getString(R.string.proj_013_location_kn),
                    getString(R.string.proj_013_budget),
                    getString(R.string.proj_013_date),
                    getString(R.string.proj_013_status_en),
                    getString(R.string.proj_013_status_kn),
                    65,
                    getString(R.string.proj_013_desc_en),
                    getString(R.string.proj_013_desc_kn),
                    getString(R.string.proj_013_before_img),
                    getString(R.string.proj_013_after_img)
                )
            )
            repository.insertProjects(allProjects)
        }
    }
}
